<?php

namespace BigFish\DeliveryGateway\GraphQL\DTO;

use BigFish\DeliveryGateway\GraphQL\EnumType;

/**
 * @method static static AD()
 * @method static static AE()
 * @method static static AF()
 * @method static static AG()
 * @method static static AI()
 * @method static static AL()
 * @method static static AM()
 * @method static static AO()
 * @method static static AQ()
 * @method static static AR()
 * @method static static AS()
 * @method static static AT()
 * @method static static AU()
 * @method static static AW()
 * @method static static AX()
 * @method static static AZ()
 * @method static static BA()
 * @method static static BB()
 * @method static static BD()
 * @method static static BE()
 * @method static static BF()
 * @method static static BG()
 * @method static static BH()
 * @method static static BI()
 * @method static static BJ()
 * @method static static BL()
 * @method static static BM()
 * @method static static BN()
 * @method static static BO()
 * @method static static BQ()
 * @method static static BR()
 * @method static static BS()
 * @method static static BT()
 * @method static static BV()
 * @method static static BW()
 * @method static static BY()
 * @method static static BZ()
 * @method static static CA()
 * @method static static CC()
 * @method static static CD()
 * @method static static CF()
 * @method static static CG()
 * @method static static CH()
 * @method static static CI()
 * @method static static CK()
 * @method static static CL()
 * @method static static CM()
 * @method static static CN()
 * @method static static CO()
 * @method static static CR()
 * @method static static CU()
 * @method static static CV()
 * @method static static CW()
 * @method static static CX()
 * @method static static CY()
 * @method static static CZ()
 * @method static static DE()
 * @method static static DJ()
 * @method static static DK()
 * @method static static DM()
 * @method static static DO()
 * @method static static DZ()
 * @method static static EC()
 * @method static static EE()
 * @method static static EG()
 * @method static static EH()
 * @method static static ER()
 * @method static static ES()
 * @method static static ET()
 * @method static static FI()
 * @method static static FJ()
 * @method static static FK()
 * @method static static FM()
 * @method static static FO()
 * @method static static FR()
 * @method static static GA()
 * @method static static GB()
 * @method static static GD()
 * @method static static GE()
 * @method static static GF()
 * @method static static GG()
 * @method static static GH()
 * @method static static GI()
 * @method static static GL()
 * @method static static GM()
 * @method static static GN()
 * @method static static GP()
 * @method static static GQ()
 * @method static static GR()
 * @method static static GS()
 * @method static static GT()
 * @method static static GU()
 * @method static static GW()
 * @method static static GY()
 * @method static static HK()
 * @method static static HM()
 * @method static static HN()
 * @method static static HR()
 * @method static static HT()
 * @method static static HU()
 * @method static static ID()
 * @method static static IE()
 * @method static static IL()
 * @method static static IM()
 * @method static static IN()
 * @method static static IO()
 * @method static static IQ()
 * @method static static IR()
 * @method static static IS()
 * @method static static IT()
 * @method static static JE()
 * @method static static JM()
 * @method static static JO()
 * @method static static JP()
 * @method static static KE()
 * @method static static KG()
 * @method static static KH()
 * @method static static KI()
 * @method static static KM()
 * @method static static KN()
 * @method static static KP()
 * @method static static KR()
 * @method static static KW()
 * @method static static KY()
 * @method static static KZ()
 * @method static static LA()
 * @method static static LB()
 * @method static static LC()
 * @method static static LI()
 * @method static static LK()
 * @method static static LR()
 * @method static static LS()
 * @method static static LT()
 * @method static static LU()
 * @method static static LV()
 * @method static static LY()
 * @method static static MA()
 * @method static static MC()
 * @method static static MD()
 * @method static static ME()
 * @method static static MF()
 * @method static static MG()
 * @method static static MH()
 * @method static static MK()
 * @method static static ML()
 * @method static static MM()
 * @method static static MN()
 * @method static static MO()
 * @method static static MP()
 * @method static static MQ()
 * @method static static MR()
 * @method static static MS()
 * @method static static MT()
 * @method static static MU()
 * @method static static MV()
 * @method static static MW()
 * @method static static MX()
 * @method static static MY()
 * @method static static MZ()
 * @method static static NA()
 * @method static static NC()
 * @method static static NE()
 * @method static static NF()
 * @method static static NG()
 * @method static static NI()
 * @method static static NL()
 * @method static static NO()
 * @method static static NP()
 * @method static static NR()
 * @method static static NU()
 * @method static static NZ()
 * @method static static OM()
 * @method static static PA()
 * @method static static PE()
 * @method static static PF()
 * @method static static PG()
 * @method static static PH()
 * @method static static PK()
 * @method static static PL()
 * @method static static PM()
 * @method static static PN()
 * @method static static PR()
 * @method static static PS()
 * @method static static PT()
 * @method static static PW()
 * @method static static PY()
 * @method static static QA()
 * @method static static RE()
 * @method static static RO()
 * @method static static RS()
 * @method static static RU()
 * @method static static RW()
 * @method static static SA()
 * @method static static SB()
 * @method static static SC()
 * @method static static SD()
 * @method static static SE()
 * @method static static SG()
 * @method static static SH()
 * @method static static SI()
 * @method static static SJ()
 * @method static static SK()
 * @method static static SL()
 * @method static static SM()
 * @method static static SN()
 * @method static static SO()
 * @method static static SR()
 * @method static static SS()
 * @method static static ST()
 * @method static static SV()
 * @method static static SX()
 * @method static static SY()
 * @method static static SZ()
 * @method static static TC()
 * @method static static TD()
 * @method static static TF()
 * @method static static TG()
 * @method static static TH()
 * @method static static TJ()
 * @method static static TK()
 * @method static static TL()
 * @method static static TM()
 * @method static static TN()
 * @method static static TO()
 * @method static static TR()
 * @method static static TT()
 * @method static static TV()
 * @method static static TW()
 * @method static static TZ()
 * @method static static UA()
 * @method static static UG()
 * @method static static UM()
 * @method static static US()
 * @method static static UY()
 * @method static static UZ()
 * @method static static VA()
 * @method static static VC()
 * @method static static VE()
 * @method static static VG()
 * @method static static VI()
 * @method static static VN()
 * @method static static VU()
 * @method static static WF()
 * @method static static WS()
 * @method static static YE()
 * @method static static YT()
 * @method static static ZA()
 * @method static static ZM()
 * @method static static ZW()
 *
 * @method bool isAd()
 * @method bool isAe()
 * @method bool isAf()
 * @method bool isAg()
 * @method bool isAi()
 * @method bool isAl()
 * @method bool isAm()
 * @method bool isAo()
 * @method bool isAq()
 * @method bool isAr()
 * @method bool isAs()
 * @method bool isAt()
 * @method bool isAu()
 * @method bool isAw()
 * @method bool isAx()
 * @method bool isAz()
 * @method bool isBa()
 * @method bool isBb()
 * @method bool isBd()
 * @method bool isBe()
 * @method bool isBf()
 * @method bool isBg()
 * @method bool isBh()
 * @method bool isBi()
 * @method bool isBj()
 * @method bool isBl()
 * @method bool isBm()
 * @method bool isBn()
 * @method bool isBo()
 * @method bool isBq()
 * @method bool isBr()
 * @method bool isBs()
 * @method bool isBt()
 * @method bool isBv()
 * @method bool isBw()
 * @method bool isBy()
 * @method bool isBz()
 * @method bool isCa()
 * @method bool isCc()
 * @method bool isCd()
 * @method bool isCf()
 * @method bool isCg()
 * @method bool isCh()
 * @method bool isCi()
 * @method bool isCk()
 * @method bool isCl()
 * @method bool isCm()
 * @method bool isCn()
 * @method bool isCo()
 * @method bool isCr()
 * @method bool isCu()
 * @method bool isCv()
 * @method bool isCw()
 * @method bool isCx()
 * @method bool isCy()
 * @method bool isCz()
 * @method bool isDe()
 * @method bool isDj()
 * @method bool isDk()
 * @method bool isDm()
 * @method bool isDo()
 * @method bool isDz()
 * @method bool isEc()
 * @method bool isEe()
 * @method bool isEg()
 * @method bool isEh()
 * @method bool isEr()
 * @method bool isEs()
 * @method bool isEt()
 * @method bool isFi()
 * @method bool isFj()
 * @method bool isFk()
 * @method bool isFm()
 * @method bool isFo()
 * @method bool isFr()
 * @method bool isGa()
 * @method bool isGb()
 * @method bool isGd()
 * @method bool isGe()
 * @method bool isGf()
 * @method bool isGg()
 * @method bool isGh()
 * @method bool isGi()
 * @method bool isGl()
 * @method bool isGm()
 * @method bool isGn()
 * @method bool isGp()
 * @method bool isGq()
 * @method bool isGr()
 * @method bool isGs()
 * @method bool isGt()
 * @method bool isGu()
 * @method bool isGw()
 * @method bool isGy()
 * @method bool isHk()
 * @method bool isHm()
 * @method bool isHn()
 * @method bool isHr()
 * @method bool isHt()
 * @method bool isHu()
 * @method bool isId()
 * @method bool isIe()
 * @method bool isIl()
 * @method bool isIm()
 * @method bool isIn()
 * @method bool isIo()
 * @method bool isIq()
 * @method bool isIr()
 * @method bool isIs()
 * @method bool isIt()
 * @method bool isJe()
 * @method bool isJm()
 * @method bool isJo()
 * @method bool isJp()
 * @method bool isKe()
 * @method bool isKg()
 * @method bool isKh()
 * @method bool isKi()
 * @method bool isKm()
 * @method bool isKn()
 * @method bool isKp()
 * @method bool isKr()
 * @method bool isKw()
 * @method bool isKy()
 * @method bool isKz()
 * @method bool isLa()
 * @method bool isLb()
 * @method bool isLc()
 * @method bool isLi()
 * @method bool isLk()
 * @method bool isLr()
 * @method bool isLs()
 * @method bool isLt()
 * @method bool isLu()
 * @method bool isLv()
 * @method bool isLy()
 * @method bool isMa()
 * @method bool isMc()
 * @method bool isMd()
 * @method bool isMe()
 * @method bool isMf()
 * @method bool isMg()
 * @method bool isMh()
 * @method bool isMk()
 * @method bool isMl()
 * @method bool isMm()
 * @method bool isMn()
 * @method bool isMo()
 * @method bool isMp()
 * @method bool isMq()
 * @method bool isMr()
 * @method bool isMs()
 * @method bool isMt()
 * @method bool isMu()
 * @method bool isMv()
 * @method bool isMw()
 * @method bool isMx()
 * @method bool isMy()
 * @method bool isMz()
 * @method bool isNa()
 * @method bool isNc()
 * @method bool isNe()
 * @method bool isNf()
 * @method bool isNg()
 * @method bool isNi()
 * @method bool isNl()
 * @method bool isNo()
 * @method bool isNp()
 * @method bool isNr()
 * @method bool isNu()
 * @method bool isNz()
 * @method bool isOm()
 * @method bool isPa()
 * @method bool isPe()
 * @method bool isPf()
 * @method bool isPg()
 * @method bool isPh()
 * @method bool isPk()
 * @method bool isPl()
 * @method bool isPm()
 * @method bool isPn()
 * @method bool isPr()
 * @method bool isPs()
 * @method bool isPt()
 * @method bool isPw()
 * @method bool isPy()
 * @method bool isQa()
 * @method bool isRe()
 * @method bool isRo()
 * @method bool isRs()
 * @method bool isRu()
 * @method bool isRw()
 * @method bool isSa()
 * @method bool isSb()
 * @method bool isSc()
 * @method bool isSd()
 * @method bool isSe()
 * @method bool isSg()
 * @method bool isSh()
 * @method bool isSi()
 * @method bool isSj()
 * @method bool isSk()
 * @method bool isSl()
 * @method bool isSm()
 * @method bool isSn()
 * @method bool isSo()
 * @method bool isSr()
 * @method bool isSs()
 * @method bool isSt()
 * @method bool isSv()
 * @method bool isSx()
 * @method bool isSy()
 * @method bool isSz()
 * @method bool isTc()
 * @method bool isTd()
 * @method bool isTf()
 * @method bool isTg()
 * @method bool isTh()
 * @method bool isTj()
 * @method bool isTk()
 * @method bool isTl()
 * @method bool isTm()
 * @method bool isTn()
 * @method bool isTo()
 * @method bool isTr()
 * @method bool isTt()
 * @method bool isTv()
 * @method bool isTw()
 * @method bool isTz()
 * @method bool isUa()
 * @method bool isUg()
 * @method bool isUm()
 * @method bool isUs()
 * @method bool isUy()
 * @method bool isUz()
 * @method bool isVa()
 * @method bool isVc()
 * @method bool isVe()
 * @method bool isVg()
 * @method bool isVi()
 * @method bool isVn()
 * @method bool isVu()
 * @method bool isWf()
 * @method bool isWs()
 * @method bool isYe()
 * @method bool isYt()
 * @method bool isZa()
 * @method bool isZm()
 * @method bool isZw()
 */
class CountryEnum extends EnumType
{
}
