<?php

namespace BigFish\DeliveryGateway\GraphQL\DTO;

use BigFish\DeliveryGateway\GraphQL\EnumType;

/**
 * @method static static AED()
 * @method static static AFN()
 * @method static static ALL()
 * @method static static AMD()
 * @method static static ANG()
 * @method static static AOA()
 * @method static static ARS()
 * @method static static AUD()
 * @method static static AWG()
 * @method static static AZN()
 * @method static static BAM()
 * @method static static BBD()
 * @method static static BDT()
 * @method static static BGN()
 * @method static static BHD()
 * @method static static BIF()
 * @method static static BMD()
 * @method static static BND()
 * @method static static BOB()
 * @method static static BOV()
 * @method static static BRL()
 * @method static static BSD()
 * @method static static BTN()
 * @method static static BWP()
 * @method static static BYN()
 * @method static static BZD()
 * @method static static CAD()
 * @method static static CDF()
 * @method static static CHE()
 * @method static static CHF()
 * @method static static CHW()
 * @method static static CLF()
 * @method static static CLP()
 * @method static static CNY()
 * @method static static COP()
 * @method static static COU()
 * @method static static CRC()
 * @method static static CUC()
 * @method static static CUP()
 * @method static static CVE()
 * @method static static CZK()
 * @method static static DJF()
 * @method static static DKK()
 * @method static static DOP()
 * @method static static DZD()
 * @method static static EGP()
 * @method static static ERN()
 * @method static static ETB()
 * @method static static EUR()
 * @method static static FJD()
 * @method static static FKP()
 * @method static static GBP()
 * @method static static GEL()
 * @method static static GHS()
 * @method static static GIP()
 * @method static static GMD()
 * @method static static GNF()
 * @method static static GTQ()
 * @method static static GYD()
 * @method static static HKD()
 * @method static static HNL()
 * @method static static HRK()
 * @method static static HTG()
 * @method static static HUF()
 * @method static static IDR()
 * @method static static ILS()
 * @method static static INR()
 * @method static static IQD()
 * @method static static IRR()
 * @method static static ISK()
 * @method static static JMD()
 * @method static static JOD()
 * @method static static JPY()
 * @method static static KES()
 * @method static static KGS()
 * @method static static KHR()
 * @method static static KMF()
 * @method static static KPW()
 * @method static static KRW()
 * @method static static KWD()
 * @method static static KYD()
 * @method static static KZT()
 * @method static static LAK()
 * @method static static LBP()
 * @method static static LKR()
 * @method static static LRD()
 * @method static static LSL()
 * @method static static LYD()
 * @method static static MAD()
 * @method static static MDL()
 * @method static static MGA()
 * @method static static MKD()
 * @method static static MMK()
 * @method static static MNT()
 * @method static static MOP()
 * @method static static MRU()
 * @method static static MUR()
 * @method static static MVR()
 * @method static static MWK()
 * @method static static MXN()
 * @method static static MXV()
 * @method static static MYR()
 * @method static static MZN()
 * @method static static NAD()
 * @method static static NGN()
 * @method static static NIO()
 * @method static static NOK()
 * @method static static NPR()
 * @method static static NZD()
 * @method static static OMR()
 * @method static static PAB()
 * @method static static PEN()
 * @method static static PGK()
 * @method static static PHP()
 * @method static static PKR()
 * @method static static PLN()
 * @method static static PYG()
 * @method static static QAR()
 * @method static static RON()
 * @method static static RSD()
 * @method static static RUB()
 * @method static static RWF()
 * @method static static SAR()
 * @method static static SBD()
 * @method static static SCR()
 * @method static static SDG()
 * @method static static SEK()
 * @method static static SGD()
 * @method static static SHP()
 * @method static static SLE()
 * @method static static SOS()
 * @method static static SRD()
 * @method static static SSP()
 * @method static static STN()
 * @method static static SVC()
 * @method static static SYP()
 * @method static static SZL()
 * @method static static THB()
 * @method static static TJS()
 * @method static static TMT()
 * @method static static TND()
 * @method static static TOP()
 * @method static static TRY()
 * @method static static TTD()
 * @method static static TWD()
 * @method static static TZS()
 * @method static static UAH()
 * @method static static UGX()
 * @method static static USD()
 * @method static static USN()
 * @method static static UYI()
 * @method static static UYU()
 * @method static static UZS()
 * @method static static VED()
 * @method static static VEF()
 * @method static static VND()
 * @method static static VUV()
 * @method static static WST()
 * @method static static XAF()
 * @method static static XCD()
 * @method static static XDR()
 * @method static static XOF()
 * @method static static XPF()
 * @method static static XSU()
 * @method static static XUA()
 * @method static static YER()
 * @method static static ZAR()
 * @method static static ZMW()
 * @method static static ZWL()
 *
 * @method bool isAed()
 * @method bool isAfn()
 * @method bool isAll()
 * @method bool isAmd()
 * @method bool isAng()
 * @method bool isAoa()
 * @method bool isArs()
 * @method bool isAud()
 * @method bool isAwg()
 * @method bool isAzn()
 * @method bool isBam()
 * @method bool isBbd()
 * @method bool isBdt()
 * @method bool isBgn()
 * @method bool isBhd()
 * @method bool isBif()
 * @method bool isBmd()
 * @method bool isBnd()
 * @method bool isBob()
 * @method bool isBov()
 * @method bool isBrl()
 * @method bool isBsd()
 * @method bool isBtn()
 * @method bool isBwp()
 * @method bool isByn()
 * @method bool isBzd()
 * @method bool isCad()
 * @method bool isCdf()
 * @method bool isChe()
 * @method bool isChf()
 * @method bool isChw()
 * @method bool isClf()
 * @method bool isClp()
 * @method bool isCny()
 * @method bool isCop()
 * @method bool isCou()
 * @method bool isCrc()
 * @method bool isCuc()
 * @method bool isCup()
 * @method bool isCve()
 * @method bool isCzk()
 * @method bool isDjf()
 * @method bool isDkk()
 * @method bool isDop()
 * @method bool isDzd()
 * @method bool isEgp()
 * @method bool isErn()
 * @method bool isEtb()
 * @method bool isEur()
 * @method bool isFjd()
 * @method bool isFkp()
 * @method bool isGbp()
 * @method bool isGel()
 * @method bool isGhs()
 * @method bool isGip()
 * @method bool isGmd()
 * @method bool isGnf()
 * @method bool isGtq()
 * @method bool isGyd()
 * @method bool isHkd()
 * @method bool isHnl()
 * @method bool isHrk()
 * @method bool isHtg()
 * @method bool isHuf()
 * @method bool isIdr()
 * @method bool isIls()
 * @method bool isInr()
 * @method bool isIqd()
 * @method bool isIrr()
 * @method bool isIsk()
 * @method bool isJmd()
 * @method bool isJod()
 * @method bool isJpy()
 * @method bool isKes()
 * @method bool isKgs()
 * @method bool isKhr()
 * @method bool isKmf()
 * @method bool isKpw()
 * @method bool isKrw()
 * @method bool isKwd()
 * @method bool isKyd()
 * @method bool isKzt()
 * @method bool isLak()
 * @method bool isLbp()
 * @method bool isLkr()
 * @method bool isLrd()
 * @method bool isLsl()
 * @method bool isLyd()
 * @method bool isMad()
 * @method bool isMdl()
 * @method bool isMga()
 * @method bool isMkd()
 * @method bool isMmk()
 * @method bool isMnt()
 * @method bool isMop()
 * @method bool isMru()
 * @method bool isMur()
 * @method bool isMvr()
 * @method bool isMwk()
 * @method bool isMxn()
 * @method bool isMxv()
 * @method bool isMyr()
 * @method bool isMzn()
 * @method bool isNad()
 * @method bool isNgn()
 * @method bool isNio()
 * @method bool isNok()
 * @method bool isNpr()
 * @method bool isNzd()
 * @method bool isOmr()
 * @method bool isPab()
 * @method bool isPen()
 * @method bool isPgk()
 * @method bool isPhp()
 * @method bool isPkr()
 * @method bool isPln()
 * @method bool isPyg()
 * @method bool isQar()
 * @method bool isRon()
 * @method bool isRsd()
 * @method bool isRub()
 * @method bool isRwf()
 * @method bool isSar()
 * @method bool isSbd()
 * @method bool isScr()
 * @method bool isSdg()
 * @method bool isSek()
 * @method bool isSgd()
 * @method bool isShp()
 * @method bool isSle()
 * @method bool isSos()
 * @method bool isSrd()
 * @method bool isSsp()
 * @method bool isStn()
 * @method bool isSvc()
 * @method bool isSyp()
 * @method bool isSzl()
 * @method bool isThb()
 * @method bool isTjs()
 * @method bool isTmt()
 * @method bool isTnd()
 * @method bool isTop()
 * @method bool isTry()
 * @method bool isTtd()
 * @method bool isTwd()
 * @method bool isTzs()
 * @method bool isUah()
 * @method bool isUgx()
 * @method bool isUsd()
 * @method bool isUsn()
 * @method bool isUyi()
 * @method bool isUyu()
 * @method bool isUzs()
 * @method bool isVed()
 * @method bool isVef()
 * @method bool isVnd()
 * @method bool isVuv()
 * @method bool isWst()
 * @method bool isXaf()
 * @method bool isXcd()
 * @method bool isXdr()
 * @method bool isXof()
 * @method bool isXpf()
 * @method bool isXsu()
 * @method bool isXua()
 * @method bool isYer()
 * @method bool isZar()
 * @method bool isZmw()
 * @method bool isZwl()
 */
class CurrencyEnum extends EnumType
{
}
