<?php

namespace BigFish\DeliveryGateway\GraphQL\DTO;

use BigFish\DeliveryGateway\GraphQL\EnumType;

/**
 * @method static static AA()
 * @method static static AB()
 * @method static static AE()
 * @method static static AF()
 * @method static static AK()
 * @method static static AM()
 * @method static static AN()
 * @method static static AR()
 * @method static static AS()
 * @method static static AV()
 * @method static static AY()
 * @method static static AZ()
 * @method static static BA()
 * @method static static BE()
 * @method static static BG()
 * @method static static BH()
 * @method static static BI()
 * @method static static BM()
 * @method static static BN()
 * @method static static BO()
 * @method static static BR()
 * @method static static BS()
 * @method static static CA()
 * @method static static CE()
 * @method static static CH()
 * @method static static CO()
 * @method static static CR()
 * @method static static CS()
 * @method static static CU()
 * @method static static CV()
 * @method static static CY()
 * @method static static DA()
 * @method static static DE()
 * @method static static DV()
 * @method static static DZ()
 * @method static static EE()
 * @method static static EL()
 * @method static static EN()
 * @method static static EO()
 * @method static static ES()
 * @method static static ET()
 * @method static static EU()
 * @method static static FA()
 * @method static static FF()
 * @method static static FI()
 * @method static static FJ()
 * @method static static FO()
 * @method static static FR()
 * @method static static FY()
 * @method static static GA()
 * @method static static GD()
 * @method static static GL()
 * @method static static GN()
 * @method static static GU()
 * @method static static GV()
 * @method static static HA()
 * @method static static HE()
 * @method static static HI()
 * @method static static HO()
 * @method static static HR()
 * @method static static HT()
 * @method static static HU()
 * @method static static HY()
 * @method static static HZ()
 * @method static static IA()
 * @method static static ID()
 * @method static static IE()
 * @method static static IG()
 * @method static static II()
 * @method static static IK()
 * @method static static IO()
 * @method static static IS()
 * @method static static IT()
 * @method static static IU()
 * @method static static JA()
 * @method static static JV()
 * @method static static KA()
 * @method static static KG()
 * @method static static KI()
 * @method static static KJ()
 * @method static static KK()
 * @method static static KL()
 * @method static static KM()
 * @method static static KN()
 * @method static static KO()
 * @method static static KR()
 * @method static static KS()
 * @method static static KU()
 * @method static static KV()
 * @method static static KW()
 * @method static static KY()
 * @method static static LA()
 * @method static static LB()
 * @method static static LG()
 * @method static static LI()
 * @method static static LN()
 * @method static static LO()
 * @method static static LT()
 * @method static static LU()
 * @method static static LV()
 * @method static static MG()
 * @method static static MH()
 * @method static static MI()
 * @method static static MK()
 * @method static static ML()
 * @method static static MN()
 * @method static static MR()
 * @method static static MS()
 * @method static static MT()
 * @method static static MY()
 * @method static static NA()
 * @method static static NB()
 * @method static static ND()
 * @method static static NE()
 * @method static static NG()
 * @method static static NL()
 * @method static static NN()
 * @method static static NO()
 * @method static static NR()
 * @method static static NV()
 * @method static static NY()
 * @method static static OC()
 * @method static static OJ()
 * @method static static OM()
 * @method static static OR()
 * @method static static OS()
 * @method static static PA()
 * @method static static PI()
 * @method static static PL()
 * @method static static PS()
 * @method static static PT()
 * @method static static QU()
 * @method static static RM()
 * @method static static RN()
 * @method static static RO()
 * @method static static RU()
 * @method static static RW()
 * @method static static SA()
 * @method static static SC()
 * @method static static SD()
 * @method static static SE()
 * @method static static SG()
 * @method static static SI()
 * @method static static SK()
 * @method static static SL()
 * @method static static SM()
 * @method static static SN()
 * @method static static SO()
 * @method static static SQ()
 * @method static static SR()
 * @method static static SS()
 * @method static static ST()
 * @method static static SU()
 * @method static static SV()
 * @method static static SW()
 * @method static static TA()
 * @method static static TE()
 * @method static static TG()
 * @method static static TH()
 * @method static static TI()
 * @method static static TK()
 * @method static static TL()
 * @method static static TN()
 * @method static static TO()
 * @method static static TR()
 * @method static static TS()
 * @method static static TT()
 * @method static static TW()
 * @method static static TY()
 * @method static static UG()
 * @method static static UK()
 * @method static static UR()
 * @method static static UZ()
 * @method static static VE()
 * @method static static VI()
 * @method static static VO()
 * @method static static WA()
 * @method static static WO()
 * @method static static XH()
 * @method static static YI()
 * @method static static YO()
 * @method static static ZA()
 * @method static static ZH()
 * @method static static ZU()
 *
 * @method bool isAa()
 * @method bool isAb()
 * @method bool isAe()
 * @method bool isAf()
 * @method bool isAk()
 * @method bool isAm()
 * @method bool isAn()
 * @method bool isAr()
 * @method bool isAs()
 * @method bool isAv()
 * @method bool isAy()
 * @method bool isAz()
 * @method bool isBa()
 * @method bool isBe()
 * @method bool isBg()
 * @method bool isBh()
 * @method bool isBi()
 * @method bool isBm()
 * @method bool isBn()
 * @method bool isBo()
 * @method bool isBr()
 * @method bool isBs()
 * @method bool isCa()
 * @method bool isCe()
 * @method bool isCh()
 * @method bool isCo()
 * @method bool isCr()
 * @method bool isCs()
 * @method bool isCu()
 * @method bool isCv()
 * @method bool isCy()
 * @method bool isDa()
 * @method bool isDe()
 * @method bool isDv()
 * @method bool isDz()
 * @method bool isEe()
 * @method bool isEl()
 * @method bool isEn()
 * @method bool isEo()
 * @method bool isEs()
 * @method bool isEt()
 * @method bool isEu()
 * @method bool isFa()
 * @method bool isFf()
 * @method bool isFi()
 * @method bool isFj()
 * @method bool isFo()
 * @method bool isFr()
 * @method bool isFy()
 * @method bool isGa()
 * @method bool isGd()
 * @method bool isGl()
 * @method bool isGn()
 * @method bool isGu()
 * @method bool isGv()
 * @method bool isHa()
 * @method bool isHe()
 * @method bool isHi()
 * @method bool isHo()
 * @method bool isHr()
 * @method bool isHt()
 * @method bool isHu()
 * @method bool isHy()
 * @method bool isHz()
 * @method bool isIa()
 * @method bool isId()
 * @method bool isIe()
 * @method bool isIg()
 * @method bool isIi()
 * @method bool isIk()
 * @method bool isIo()
 * @method bool isIs()
 * @method bool isIt()
 * @method bool isIu()
 * @method bool isJa()
 * @method bool isJv()
 * @method bool isKa()
 * @method bool isKg()
 * @method bool isKi()
 * @method bool isKj()
 * @method bool isKk()
 * @method bool isKl()
 * @method bool isKm()
 * @method bool isKn()
 * @method bool isKo()
 * @method bool isKr()
 * @method bool isKs()
 * @method bool isKu()
 * @method bool isKv()
 * @method bool isKw()
 * @method bool isKy()
 * @method bool isLa()
 * @method bool isLb()
 * @method bool isLg()
 * @method bool isLi()
 * @method bool isLn()
 * @method bool isLo()
 * @method bool isLt()
 * @method bool isLu()
 * @method bool isLv()
 * @method bool isMg()
 * @method bool isMh()
 * @method bool isMi()
 * @method bool isMk()
 * @method bool isMl()
 * @method bool isMn()
 * @method bool isMr()
 * @method bool isMs()
 * @method bool isMt()
 * @method bool isMy()
 * @method bool isNa()
 * @method bool isNb()
 * @method bool isNd()
 * @method bool isNe()
 * @method bool isNg()
 * @method bool isNl()
 * @method bool isNn()
 * @method bool isNo()
 * @method bool isNr()
 * @method bool isNv()
 * @method bool isNy()
 * @method bool isOc()
 * @method bool isOj()
 * @method bool isOm()
 * @method bool isOr()
 * @method bool isOs()
 * @method bool isPa()
 * @method bool isPi()
 * @method bool isPl()
 * @method bool isPs()
 * @method bool isPt()
 * @method bool isQu()
 * @method bool isRm()
 * @method bool isRn()
 * @method bool isRo()
 * @method bool isRu()
 * @method bool isRw()
 * @method bool isSa()
 * @method bool isSc()
 * @method bool isSd()
 * @method bool isSe()
 * @method bool isSg()
 * @method bool isSi()
 * @method bool isSk()
 * @method bool isSl()
 * @method bool isSm()
 * @method bool isSn()
 * @method bool isSo()
 * @method bool isSq()
 * @method bool isSr()
 * @method bool isSs()
 * @method bool isSt()
 * @method bool isSu()
 * @method bool isSv()
 * @method bool isSw()
 * @method bool isTa()
 * @method bool isTe()
 * @method bool isTg()
 * @method bool isTh()
 * @method bool isTi()
 * @method bool isTk()
 * @method bool isTl()
 * @method bool isTn()
 * @method bool isTo()
 * @method bool isTr()
 * @method bool isTs()
 * @method bool isTt()
 * @method bool isTw()
 * @method bool isTy()
 * @method bool isUg()
 * @method bool isUk()
 * @method bool isUr()
 * @method bool isUz()
 * @method bool isVe()
 * @method bool isVi()
 * @method bool isVo()
 * @method bool isWa()
 * @method bool isWo()
 * @method bool isXh()
 * @method bool isYi()
 * @method bool isYo()
 * @method bool isZa()
 * @method bool isZh()
 * @method bool isZu()
 */
class LanguageEnum extends EnumType
{
}
