<?php

namespace BigFish\DeliveryGateway\GraphQL\DTO;

use BigFish\DeliveryGateway\GraphQL\EnumType;

/**
 * @method static static ALZA_BOX()
 * @method static static AVANTI()
 * @method static static AVIA()
 * @method static static COOP()
 * @method static static CORNER()
 * @method static static DHL()
 * @method static static DPD()
 * @method static static EXPRESS_ONE()
 * @method static static FED_EX()
 * @method static static FOX_POST()
 * @method static static GLS()
 * @method static static MEDIA_MARKT()
 * @method static static MOL()
 * @method static static MPL()
 * @method static static OMV()
 * @method static static OTHER()
 * @method static static PACKETA()
 * @method static static PATRONBOLT()
 * @method static static PLAYERSROOM()
 * @method static static PLAYMAX()
 * @method static static REAL()
 * @method static static RELAY_INMEDIO()
 * @method static static ROBOT_GURU()
 * @method static static SAME_DAY()
 * @method static static SPORTFACTORY()
 * @method static static SPRINTER()
 * @method static static TNT()
 * @method static static TRANS_SPED()
 * @method static static TWO_TWO_ZERO_VOLT()
 * @method static static UPS()
 *
 * @method bool isAlzaBox()
 * @method bool isAvanti()
 * @method bool isAvia()
 * @method bool isCoop()
 * @method bool isCorner()
 * @method bool isDhl()
 * @method bool isDpd()
 * @method bool isExpressOne()
 * @method bool isFedEx()
 * @method bool isFoxPost()
 * @method bool isGls()
 * @method bool isMediaMarkt()
 * @method bool isMol()
 * @method bool isMpl()
 * @method bool isOmv()
 * @method bool isOther()
 * @method bool isPacketa()
 * @method bool isPatronbolt()
 * @method bool isPlayersroom()
 * @method bool isPlaymax()
 * @method bool isReal()
 * @method bool isRelayInmedio()
 * @method bool isRobotGuru()
 * @method bool isSameDay()
 * @method bool isSportfactory()
 * @method bool isSprinter()
 * @method bool isTnt()
 * @method bool isTransSped()
 * @method bool isTwoTwoZeroVolt()
 * @method bool isUps()
 */
class OperatorEnum extends EnumType
{
}
