<?php

namespace BigFish\DeliveryGateway\GraphQL\DTO;

use BigFish\DeliveryGateway\GraphQL\EnumType;

/**
 * @method static static AFRICA_ABIDJAN()
 * @method static static AFRICA_ALGIERS()
 * @method static static AFRICA_BISSAU()
 * @method static static AFRICA_CAIRO()
 * @method static static AFRICA_CASABLANCA()
 * @method static static AFRICA_CEUTA()
 * @method static static AFRICA_EL_AAIUN()
 * @method static static AFRICA_JOHANNESBURG()
 * @method static static AFRICA_JUBA()
 * @method static static AFRICA_KHARTOUM()
 * @method static static AFRICA_LAGOS()
 * @method static static AFRICA_MAPUTO()
 * @method static static AFRICA_MONROVIA()
 * @method static static AFRICA_NAIROBI()
 * @method static static AFRICA_NDJAMENA()
 * @method static static AFRICA_SAO_TOME()
 * @method static static AFRICA_TRIPOLI()
 * @method static static AFRICA_TUNIS()
 * @method static static AFRICA_WINDHOEK()
 * @method static static AMERICA_ADAK()
 * @method static static AMERICA_ANCHORAGE()
 * @method static static AMERICA_ARAGUAINA()
 * @method static static AMERICA_ARGENTINA_BUENOS_AIRES()
 * @method static static AMERICA_ARGENTINA_CATAMARCA()
 * @method static static AMERICA_ARGENTINA_CORDOBA()
 * @method static static AMERICA_ARGENTINA_JUJUY()
 * @method static static AMERICA_ARGENTINA_LA_RIOJA()
 * @method static static AMERICA_ARGENTINA_MENDOZA()
 * @method static static AMERICA_ARGENTINA_RIO_GALLEGOS()
 * @method static static AMERICA_ARGENTINA_SALTA()
 * @method static static AMERICA_ARGENTINA_SAN_JUAN()
 * @method static static AMERICA_ARGENTINA_SAN_LUIS()
 * @method static static AMERICA_ARGENTINA_TUCUMAN()
 * @method static static AMERICA_ARGENTINA_USHUAIA()
 * @method static static AMERICA_ASUNCION()
 * @method static static AMERICA_BAHIA()
 * @method static static AMERICA_BAHIA_BANDERAS()
 * @method static static AMERICA_BARBADOS()
 * @method static static AMERICA_BELEM()
 * @method static static AMERICA_BELIZE()
 * @method static static AMERICA_BOA_VISTA()
 * @method static static AMERICA_BOGOTA()
 * @method static static AMERICA_BOISE()
 * @method static static AMERICA_CAMBRIDGE_BAY()
 * @method static static AMERICA_CAMPO_GRANDE()
 * @method static static AMERICA_CANCUN()
 * @method static static AMERICA_CARACAS()
 * @method static static AMERICA_CAYENNE()
 * @method static static AMERICA_CHICAGO()
 * @method static static AMERICA_CHIHUAHUA()
 * @method static static AMERICA_CIUDAD_JUAREZ()
 * @method static static AMERICA_COSTA_RICA()
 * @method static static AMERICA_CUIABA()
 * @method static static AMERICA_DANMARKSHAVN()
 * @method static static AMERICA_DAWSON()
 * @method static static AMERICA_DAWSON_CREEK()
 * @method static static AMERICA_DENVER()
 * @method static static AMERICA_DETROIT()
 * @method static static AMERICA_EDMONTON()
 * @method static static AMERICA_EIRUNEPE()
 * @method static static AMERICA_EL_SALVADOR()
 * @method static static AMERICA_FORTALEZA()
 * @method static static AMERICA_FORT_NELSON()
 * @method static static AMERICA_GLACE_BAY()
 * @method static static AMERICA_GOOSE_BAY()
 * @method static static AMERICA_GRAND_TURK()
 * @method static static AMERICA_GUATEMALA()
 * @method static static AMERICA_GUAYAQUIL()
 * @method static static AMERICA_GUYANA()
 * @method static static AMERICA_HALIFAX()
 * @method static static AMERICA_HAVANA()
 * @method static static AMERICA_HERMOSILLO()
 * @method static static AMERICA_INDIANA_INDIANAPOLIS()
 * @method static static AMERICA_INDIANA_KNOX()
 * @method static static AMERICA_INDIANA_MARENGO()
 * @method static static AMERICA_INDIANA_PETERSBURG()
 * @method static static AMERICA_INDIANA_TELL_CITY()
 * @method static static AMERICA_INDIANA_VEVAY()
 * @method static static AMERICA_INDIANA_VINCENNES()
 * @method static static AMERICA_INDIANA_WINAMAC()
 * @method static static AMERICA_INUVIK()
 * @method static static AMERICA_IQALUIT()
 * @method static static AMERICA_JAMAICA()
 * @method static static AMERICA_JUNEAU()
 * @method static static AMERICA_KENTUCKY_LOUISVILLE()
 * @method static static AMERICA_KENTUCKY_MONTICELLO()
 * @method static static AMERICA_LA_PAZ()
 * @method static static AMERICA_LIMA()
 * @method static static AMERICA_LOS_ANGELES()
 * @method static static AMERICA_MACEIO()
 * @method static static AMERICA_MANAGUA()
 * @method static static AMERICA_MANAUS()
 * @method static static AMERICA_MARTINIQUE()
 * @method static static AMERICA_MATAMOROS()
 * @method static static AMERICA_MAZATLAN()
 * @method static static AMERICA_MENOMINEE()
 * @method static static AMERICA_MERIDA()
 * @method static static AMERICA_METLAKATLA()
 * @method static static AMERICA_MEXICO_CITY()
 * @method static static AMERICA_MIQUELON()
 * @method static static AMERICA_MONCTON()
 * @method static static AMERICA_MONTERREY()
 * @method static static AMERICA_MONTEVIDEO()
 * @method static static AMERICA_NEW_YORK()
 * @method static static AMERICA_NOME()
 * @method static static AMERICA_NORONHA()
 * @method static static AMERICA_NORTH_DAKOTA_BEULAH()
 * @method static static AMERICA_NORTH_DAKOTA_CENTER()
 * @method static static AMERICA_NORTH_DAKOTA_NEW_SALEM()
 * @method static static AMERICA_NUUK()
 * @method static static AMERICA_OJINAGA()
 * @method static static AMERICA_PANAMA()
 * @method static static AMERICA_PARAMARIBO()
 * @method static static AMERICA_PHOENIX()
 * @method static static AMERICA_PORTAU_PRINCE()
 * @method static static AMERICA_PORTO_VELHO()
 * @method static static AMERICA_PUERTO_RICO()
 * @method static static AMERICA_PUNTA_ARENAS()
 * @method static static AMERICA_RANKIN_INLET()
 * @method static static AMERICA_RECIFE()
 * @method static static AMERICA_REGINA()
 * @method static static AMERICA_RESOLUTE()
 * @method static static AMERICA_RIO_BRANCO()
 * @method static static AMERICA_SANTAREM()
 * @method static static AMERICA_SANTIAGO()
 * @method static static AMERICA_SANTO_DOMINGO()
 * @method static static AMERICA_SAO_PAULO()
 * @method static static AMERICA_SCORESBYSUND()
 * @method static static AMERICA_SITKA()
 * @method static static AMERICA_ST_JOHNS()
 * @method static static AMERICA_SWIFT_CURRENT()
 * @method static static AMERICA_TEGUCIGALPA()
 * @method static static AMERICA_THULE()
 * @method static static AMERICA_TIJUANA()
 * @method static static AMERICA_TORONTO()
 * @method static static AMERICA_VANCOUVER()
 * @method static static AMERICA_WHITEHORSE()
 * @method static static AMERICA_WINNIPEG()
 * @method static static AMERICA_YAKUTAT()
 * @method static static ANTARCTICA_CASEY()
 * @method static static ANTARCTICA_DAVIS()
 * @method static static ANTARCTICA_MACQUARIE()
 * @method static static ANTARCTICA_MAWSON()
 * @method static static ANTARCTICA_PALMER()
 * @method static static ANTARCTICA_ROTHERA()
 * @method static static ANTARCTICA_TROLL()
 * @method static static ASIA_ALMATY()
 * @method static static ASIA_AMMAN()
 * @method static static ASIA_ANADYR()
 * @method static static ASIA_AQTAU()
 * @method static static ASIA_AQTOBE()
 * @method static static ASIA_ASHGABAT()
 * @method static static ASIA_ATYRAU()
 * @method static static ASIA_BAGHDAD()
 * @method static static ASIA_BAKU()
 * @method static static ASIA_BANGKOK()
 * @method static static ASIA_BARNAUL()
 * @method static static ASIA_BEIRUT()
 * @method static static ASIA_BISHKEK()
 * @method static static ASIA_CHITA()
 * @method static static ASIA_CHOIBALSAN()
 * @method static static ASIA_COLOMBO()
 * @method static static ASIA_DAMASCUS()
 * @method static static ASIA_DHAKA()
 * @method static static ASIA_DILI()
 * @method static static ASIA_DUBAI()
 * @method static static ASIA_DUSHANBE()
 * @method static static ASIA_FAMAGUSTA()
 * @method static static ASIA_GAZA()
 * @method static static ASIA_HEBRON()
 * @method static static ASIA_HONG_KONG()
 * @method static static ASIA_HOVD()
 * @method static static ASIA_HO_CHI_MINH()
 * @method static static ASIA_IRKUTSK()
 * @method static static ASIA_JAKARTA()
 * @method static static ASIA_JAYAPURA()
 * @method static static ASIA_JERUSALEM()
 * @method static static ASIA_KABUL()
 * @method static static ASIA_KAMCHATKA()
 * @method static static ASIA_KARACHI()
 * @method static static ASIA_KATHMANDU()
 * @method static static ASIA_KHANDYGA()
 * @method static static ASIA_KOLKATA()
 * @method static static ASIA_KRASNOYARSK()
 * @method static static ASIA_KUCHING()
 * @method static static ASIA_MACAU()
 * @method static static ASIA_MAGADAN()
 * @method static static ASIA_MAKASSAR()
 * @method static static ASIA_MANILA()
 * @method static static ASIA_NICOSIA()
 * @method static static ASIA_NOVOKUZNETSK()
 * @method static static ASIA_NOVOSIBIRSK()
 * @method static static ASIA_OMSK()
 * @method static static ASIA_ORAL()
 * @method static static ASIA_PONTIANAK()
 * @method static static ASIA_PYONGYANG()
 * @method static static ASIA_QATAR()
 * @method static static ASIA_QOSTANAY()
 * @method static static ASIA_QYZYLORDA()
 * @method static static ASIA_RIYADH()
 * @method static static ASIA_SAKHALIN()
 * @method static static ASIA_SAMARKAND()
 * @method static static ASIA_SEOUL()
 * @method static static ASIA_SHANGHAI()
 * @method static static ASIA_SINGAPORE()
 * @method static static ASIA_SREDNEKOLYMSK()
 * @method static static ASIA_TAIPEI()
 * @method static static ASIA_TASHKENT()
 * @method static static ASIA_TBILISI()
 * @method static static ASIA_TEHRAN()
 * @method static static ASIA_THIMPHU()
 * @method static static ASIA_TOKYO()
 * @method static static ASIA_TOMSK()
 * @method static static ASIA_ULAANBAATAR()
 * @method static static ASIA_URUMQI()
 * @method static static ASIA_UST_NERA()
 * @method static static ASIA_VLADIVOSTOK()
 * @method static static ASIA_YAKUTSK()
 * @method static static ASIA_YANGON()
 * @method static static ASIA_YEKATERINBURG()
 * @method static static ASIA_YEREVAN()
 * @method static static ATLANTIC_AZORES()
 * @method static static ATLANTIC_BERMUDA()
 * @method static static ATLANTIC_CANARY()
 * @method static static ATLANTIC_CAPE_VERDE()
 * @method static static ATLANTIC_FAROE()
 * @method static static ATLANTIC_MADEIRA()
 * @method static static ATLANTIC_SOUTH_GEORGIA()
 * @method static static ATLANTIC_STANLEY()
 * @method static static AUSTRALIA_ADELAIDE()
 * @method static static AUSTRALIA_BRISBANE()
 * @method static static AUSTRALIA_BROKEN_HILL()
 * @method static static AUSTRALIA_DARWIN()
 * @method static static AUSTRALIA_EUCLA()
 * @method static static AUSTRALIA_HOBART()
 * @method static static AUSTRALIA_LINDEMAN()
 * @method static static AUSTRALIA_LORD_HOWE()
 * @method static static AUSTRALIA_MELBOURNE()
 * @method static static AUSTRALIA_PERTH()
 * @method static static AUSTRALIA_SYDNEY()
 * @method static static EUROPE_ANDORRA()
 * @method static static EUROPE_ASTRAKHAN()
 * @method static static EUROPE_ATHENS()
 * @method static static EUROPE_BELGRADE()
 * @method static static EUROPE_BERLIN()
 * @method static static EUROPE_BRUSSELS()
 * @method static static EUROPE_BUCHAREST()
 * @method static static EUROPE_BUDAPEST()
 * @method static static EUROPE_CHISINAU()
 * @method static static EUROPE_DUBLIN()
 * @method static static EUROPE_GIBRALTAR()
 * @method static static EUROPE_HELSINKI()
 * @method static static EUROPE_ISTANBUL()
 * @method static static EUROPE_KALININGRAD()
 * @method static static EUROPE_KIROV()
 * @method static static EUROPE_KYIV()
 * @method static static EUROPE_LISBON()
 * @method static static EUROPE_LONDON()
 * @method static static EUROPE_MADRID()
 * @method static static EUROPE_MALTA()
 * @method static static EUROPE_MINSK()
 * @method static static EUROPE_MOSCOW()
 * @method static static EUROPE_PARIS()
 * @method static static EUROPE_PRAGUE()
 * @method static static EUROPE_RIGA()
 * @method static static EUROPE_ROME()
 * @method static static EUROPE_SAMARA()
 * @method static static EUROPE_SARATOV()
 * @method static static EUROPE_SIMFEROPOL()
 * @method static static EUROPE_SOFIA()
 * @method static static EUROPE_TALLINN()
 * @method static static EUROPE_TIRANE()
 * @method static static EUROPE_ULYANOVSK()
 * @method static static EUROPE_VIENNA()
 * @method static static EUROPE_VILNIUS()
 * @method static static EUROPE_VOLGOGRAD()
 * @method static static EUROPE_WARSAW()
 * @method static static EUROPE_ZURICH()
 * @method static static INDIAN_CHAGOS()
 * @method static static INDIAN_MALDIVES()
 * @method static static INDIAN_MAURITIUS()
 * @method static static PACIFIC_APIA()
 * @method static static PACIFIC_AUCKLAND()
 * @method static static PACIFIC_BOUGAINVILLE()
 * @method static static PACIFIC_CHATHAM()
 * @method static static PACIFIC_EASTER()
 * @method static static PACIFIC_EFATE()
 * @method static static PACIFIC_FAKAOFO()
 * @method static static PACIFIC_FIJI()
 * @method static static PACIFIC_GALAPAGOS()
 * @method static static PACIFIC_GAMBIER()
 * @method static static PACIFIC_GUADALCANAL()
 * @method static static PACIFIC_GUAM()
 * @method static static PACIFIC_HONOLULU()
 * @method static static PACIFIC_KANTON()
 * @method static static PACIFIC_KIRITIMATI()
 * @method static static PACIFIC_KOSRAE()
 * @method static static PACIFIC_KWAJALEIN()
 * @method static static PACIFIC_MARQUESAS()
 * @method static static PACIFIC_NAURU()
 * @method static static PACIFIC_NIUE()
 * @method static static PACIFIC_NORFOLK()
 * @method static static PACIFIC_NOUMEA()
 * @method static static PACIFIC_PAGO_PAGO()
 * @method static static PACIFIC_PALAU()
 * @method static static PACIFIC_PITCAIRN()
 * @method static static PACIFIC_PORT_MORESBY()
 * @method static static PACIFIC_RAROTONGA()
 * @method static static PACIFIC_TAHITI()
 * @method static static PACIFIC_TARAWA()
 * @method static static PACIFIC_TONGATAPU()
 *
 * @method bool isAfricaAbidjan()
 * @method bool isAfricaAlgiers()
 * @method bool isAfricaBissau()
 * @method bool isAfricaCairo()
 * @method bool isAfricaCasablanca()
 * @method bool isAfricaCeuta()
 * @method bool isAfricaElAaiun()
 * @method bool isAfricaJohannesburg()
 * @method bool isAfricaJuba()
 * @method bool isAfricaKhartoum()
 * @method bool isAfricaLagos()
 * @method bool isAfricaMaputo()
 * @method bool isAfricaMonrovia()
 * @method bool isAfricaNairobi()
 * @method bool isAfricaNdjamena()
 * @method bool isAfricaSaoTome()
 * @method bool isAfricaTripoli()
 * @method bool isAfricaTunis()
 * @method bool isAfricaWindhoek()
 * @method bool isAmericaAdak()
 * @method bool isAmericaAnchorage()
 * @method bool isAmericaAraguaina()
 * @method bool isAmericaArgentinaBuenosAires()
 * @method bool isAmericaArgentinaCatamarca()
 * @method bool isAmericaArgentinaCordoba()
 * @method bool isAmericaArgentinaJujuy()
 * @method bool isAmericaArgentinaLaRioja()
 * @method bool isAmericaArgentinaMendoza()
 * @method bool isAmericaArgentinaRioGallegos()
 * @method bool isAmericaArgentinaSalta()
 * @method bool isAmericaArgentinaSanJuan()
 * @method bool isAmericaArgentinaSanLuis()
 * @method bool isAmericaArgentinaTucuman()
 * @method bool isAmericaArgentinaUshuaia()
 * @method bool isAmericaAsuncion()
 * @method bool isAmericaBahia()
 * @method bool isAmericaBahiaBanderas()
 * @method bool isAmericaBarbados()
 * @method bool isAmericaBelem()
 * @method bool isAmericaBelize()
 * @method bool isAmericaBoaVista()
 * @method bool isAmericaBogota()
 * @method bool isAmericaBoise()
 * @method bool isAmericaCambridgeBay()
 * @method bool isAmericaCampoGrande()
 * @method bool isAmericaCancun()
 * @method bool isAmericaCaracas()
 * @method bool isAmericaCayenne()
 * @method bool isAmericaChicago()
 * @method bool isAmericaChihuahua()
 * @method bool isAmericaCiudadJuarez()
 * @method bool isAmericaCostaRica()
 * @method bool isAmericaCuiaba()
 * @method bool isAmericaDanmarkshavn()
 * @method bool isAmericaDawson()
 * @method bool isAmericaDawsonCreek()
 * @method bool isAmericaDenver()
 * @method bool isAmericaDetroit()
 * @method bool isAmericaEdmonton()
 * @method bool isAmericaEirunepe()
 * @method bool isAmericaElSalvador()
 * @method bool isAmericaFortaleza()
 * @method bool isAmericaFortNelson()
 * @method bool isAmericaGlaceBay()
 * @method bool isAmericaGooseBay()
 * @method bool isAmericaGrandTurk()
 * @method bool isAmericaGuatemala()
 * @method bool isAmericaGuayaquil()
 * @method bool isAmericaGuyana()
 * @method bool isAmericaHalifax()
 * @method bool isAmericaHavana()
 * @method bool isAmericaHermosillo()
 * @method bool isAmericaIndianaIndianapolis()
 * @method bool isAmericaIndianaKnox()
 * @method bool isAmericaIndianaMarengo()
 * @method bool isAmericaIndianaPetersburg()
 * @method bool isAmericaIndianaTellCity()
 * @method bool isAmericaIndianaVevay()
 * @method bool isAmericaIndianaVincennes()
 * @method bool isAmericaIndianaWinamac()
 * @method bool isAmericaInuvik()
 * @method bool isAmericaIqaluit()
 * @method bool isAmericaJamaica()
 * @method bool isAmericaJuneau()
 * @method bool isAmericaKentuckyLouisville()
 * @method bool isAmericaKentuckyMonticello()
 * @method bool isAmericaLaPaz()
 * @method bool isAmericaLima()
 * @method bool isAmericaLosAngeles()
 * @method bool isAmericaMaceio()
 * @method bool isAmericaManagua()
 * @method bool isAmericaManaus()
 * @method bool isAmericaMartinique()
 * @method bool isAmericaMatamoros()
 * @method bool isAmericaMazatlan()
 * @method bool isAmericaMenominee()
 * @method bool isAmericaMerida()
 * @method bool isAmericaMetlakatla()
 * @method bool isAmericaMexicoCity()
 * @method bool isAmericaMiquelon()
 * @method bool isAmericaMoncton()
 * @method bool isAmericaMonterrey()
 * @method bool isAmericaMontevideo()
 * @method bool isAmericaNewYork()
 * @method bool isAmericaNome()
 * @method bool isAmericaNoronha()
 * @method bool isAmericaNorthDakotaBeulah()
 * @method bool isAmericaNorthDakotaCenter()
 * @method bool isAmericaNorthDakotaNewSalem()
 * @method bool isAmericaNuuk()
 * @method bool isAmericaOjinaga()
 * @method bool isAmericaPanama()
 * @method bool isAmericaParamaribo()
 * @method bool isAmericaPhoenix()
 * @method bool isAmericaPortauPrince()
 * @method bool isAmericaPortoVelho()
 * @method bool isAmericaPuertoRico()
 * @method bool isAmericaPuntaArenas()
 * @method bool isAmericaRankinInlet()
 * @method bool isAmericaRecife()
 * @method bool isAmericaRegina()
 * @method bool isAmericaResolute()
 * @method bool isAmericaRioBranco()
 * @method bool isAmericaSantarem()
 * @method bool isAmericaSantiago()
 * @method bool isAmericaSantoDomingo()
 * @method bool isAmericaSaoPaulo()
 * @method bool isAmericaScoresbysund()
 * @method bool isAmericaSitka()
 * @method bool isAmericaStJohns()
 * @method bool isAmericaSwiftCurrent()
 * @method bool isAmericaTegucigalpa()
 * @method bool isAmericaThule()
 * @method bool isAmericaTijuana()
 * @method bool isAmericaToronto()
 * @method bool isAmericaVancouver()
 * @method bool isAmericaWhitehorse()
 * @method bool isAmericaWinnipeg()
 * @method bool isAmericaYakutat()
 * @method bool isAntarcticaCasey()
 * @method bool isAntarcticaDavis()
 * @method bool isAntarcticaMacquarie()
 * @method bool isAntarcticaMawson()
 * @method bool isAntarcticaPalmer()
 * @method bool isAntarcticaRothera()
 * @method bool isAntarcticaTroll()
 * @method bool isAsiaAlmaty()
 * @method bool isAsiaAmman()
 * @method bool isAsiaAnadyr()
 * @method bool isAsiaAqtau()
 * @method bool isAsiaAqtobe()
 * @method bool isAsiaAshgabat()
 * @method bool isAsiaAtyrau()
 * @method bool isAsiaBaghdad()
 * @method bool isAsiaBaku()
 * @method bool isAsiaBangkok()
 * @method bool isAsiaBarnaul()
 * @method bool isAsiaBeirut()
 * @method bool isAsiaBishkek()
 * @method bool isAsiaChita()
 * @method bool isAsiaChoibalsan()
 * @method bool isAsiaColombo()
 * @method bool isAsiaDamascus()
 * @method bool isAsiaDhaka()
 * @method bool isAsiaDili()
 * @method bool isAsiaDubai()
 * @method bool isAsiaDushanbe()
 * @method bool isAsiaFamagusta()
 * @method bool isAsiaGaza()
 * @method bool isAsiaHebron()
 * @method bool isAsiaHongKong()
 * @method bool isAsiaHovd()
 * @method bool isAsiaHoChiMinh()
 * @method bool isAsiaIrkutsk()
 * @method bool isAsiaJakarta()
 * @method bool isAsiaJayapura()
 * @method bool isAsiaJerusalem()
 * @method bool isAsiaKabul()
 * @method bool isAsiaKamchatka()
 * @method bool isAsiaKarachi()
 * @method bool isAsiaKathmandu()
 * @method bool isAsiaKhandyga()
 * @method bool isAsiaKolkata()
 * @method bool isAsiaKrasnoyarsk()
 * @method bool isAsiaKuching()
 * @method bool isAsiaMacau()
 * @method bool isAsiaMagadan()
 * @method bool isAsiaMakassar()
 * @method bool isAsiaManila()
 * @method bool isAsiaNicosia()
 * @method bool isAsiaNovokuznetsk()
 * @method bool isAsiaNovosibirsk()
 * @method bool isAsiaOmsk()
 * @method bool isAsiaOral()
 * @method bool isAsiaPontianak()
 * @method bool isAsiaPyongyang()
 * @method bool isAsiaQatar()
 * @method bool isAsiaQostanay()
 * @method bool isAsiaQyzylorda()
 * @method bool isAsiaRiyadh()
 * @method bool isAsiaSakhalin()
 * @method bool isAsiaSamarkand()
 * @method bool isAsiaSeoul()
 * @method bool isAsiaShanghai()
 * @method bool isAsiaSingapore()
 * @method bool isAsiaSrednekolymsk()
 * @method bool isAsiaTaipei()
 * @method bool isAsiaTashkent()
 * @method bool isAsiaTbilisi()
 * @method bool isAsiaTehran()
 * @method bool isAsiaThimphu()
 * @method bool isAsiaTokyo()
 * @method bool isAsiaTomsk()
 * @method bool isAsiaUlaanbaatar()
 * @method bool isAsiaUrumqi()
 * @method bool isAsiaUstNera()
 * @method bool isAsiaVladivostok()
 * @method bool isAsiaYakutsk()
 * @method bool isAsiaYangon()
 * @method bool isAsiaYekaterinburg()
 * @method bool isAsiaYerevan()
 * @method bool isAtlanticAzores()
 * @method bool isAtlanticBermuda()
 * @method bool isAtlanticCanary()
 * @method bool isAtlanticCapeVerde()
 * @method bool isAtlanticFaroe()
 * @method bool isAtlanticMadeira()
 * @method bool isAtlanticSouthGeorgia()
 * @method bool isAtlanticStanley()
 * @method bool isAustraliaAdelaide()
 * @method bool isAustraliaBrisbane()
 * @method bool isAustraliaBrokenHill()
 * @method bool isAustraliaDarwin()
 * @method bool isAustraliaEucla()
 * @method bool isAustraliaHobart()
 * @method bool isAustraliaLindeman()
 * @method bool isAustraliaLordHowe()
 * @method bool isAustraliaMelbourne()
 * @method bool isAustraliaPerth()
 * @method bool isAustraliaSydney()
 * @method bool isEuropeAndorra()
 * @method bool isEuropeAstrakhan()
 * @method bool isEuropeAthens()
 * @method bool isEuropeBelgrade()
 * @method bool isEuropeBerlin()
 * @method bool isEuropeBrussels()
 * @method bool isEuropeBucharest()
 * @method bool isEuropeBudapest()
 * @method bool isEuropeChisinau()
 * @method bool isEuropeDublin()
 * @method bool isEuropeGibraltar()
 * @method bool isEuropeHelsinki()
 * @method bool isEuropeIstanbul()
 * @method bool isEuropeKaliningrad()
 * @method bool isEuropeKirov()
 * @method bool isEuropeKyiv()
 * @method bool isEuropeLisbon()
 * @method bool isEuropeLondon()
 * @method bool isEuropeMadrid()
 * @method bool isEuropeMalta()
 * @method bool isEuropeMinsk()
 * @method bool isEuropeMoscow()
 * @method bool isEuropeParis()
 * @method bool isEuropePrague()
 * @method bool isEuropeRiga()
 * @method bool isEuropeRome()
 * @method bool isEuropeSamara()
 * @method bool isEuropeSaratov()
 * @method bool isEuropeSimferopol()
 * @method bool isEuropeSofia()
 * @method bool isEuropeTallinn()
 * @method bool isEuropeTirane()
 * @method bool isEuropeUlyanovsk()
 * @method bool isEuropeVienna()
 * @method bool isEuropeVilnius()
 * @method bool isEuropeVolgograd()
 * @method bool isEuropeWarsaw()
 * @method bool isEuropeZurich()
 * @method bool isIndianChagos()
 * @method bool isIndianMaldives()
 * @method bool isIndianMauritius()
 * @method bool isPacificApia()
 * @method bool isPacificAuckland()
 * @method bool isPacificBougainville()
 * @method bool isPacificChatham()
 * @method bool isPacificEaster()
 * @method bool isPacificEfate()
 * @method bool isPacificFakaofo()
 * @method bool isPacificFiji()
 * @method bool isPacificGalapagos()
 * @method bool isPacificGambier()
 * @method bool isPacificGuadalcanal()
 * @method bool isPacificGuam()
 * @method bool isPacificHonolulu()
 * @method bool isPacificKanton()
 * @method bool isPacificKiritimati()
 * @method bool isPacificKosrae()
 * @method bool isPacificKwajalein()
 * @method bool isPacificMarquesas()
 * @method bool isPacificNauru()
 * @method bool isPacificNiue()
 * @method bool isPacificNorfolk()
 * @method bool isPacificNoumea()
 * @method bool isPacificPagoPago()
 * @method bool isPacificPalau()
 * @method bool isPacificPitcairn()
 * @method bool isPacificPortMoresby()
 * @method bool isPacificRarotonga()
 * @method bool isPacificTahiti()
 * @method bool isPacificTarawa()
 * @method bool isPacificTongatapu()
 */
class TimezoneEnum extends EnumType
{
}
